controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /
    controller: App\Controller\CidadaoController::index
    methods: ['GET', 'POST']

pesquisa:
    path: /pesquisa
    controller: App\Controller\CidadaoController::pesquisa
    methods: ['GET']